# Generated by Django 3.0.7 on 2021-03-27 08:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('Low', 'L'), ('Medium', 'M'), ('High', 'H')], max_length=8)),
                ('no_of_days', models.IntegerField(validators=[app.models.check_type])),
            ],
        ),
    ]
